# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'programming.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgrammerDialog(object):
    def setupUi(self, ProgrammerDialog):
        ProgrammerDialog.setObjectName("ProgrammerDialog")
        ProgrammerDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ProgrammerDialog.resize(400, 115)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ProgrammerDialog.sizePolicy().hasHeightForWidth())
        ProgrammerDialog.setSizePolicy(sizePolicy)
        ProgrammerDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProgrammerDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.program_progress = QtWidgets.QProgressBar(ProgrammerDialog)
        self.program_progress.setProperty("value", 0)
        self.program_progress.setObjectName("program_progress")
        self.verticalLayout.addWidget(self.program_progress)
        self.programmer_cb = QComboBoxExtra(ProgrammerDialog)
        self.programmer_cb.setEnabled(False)
        self.programmer_cb.setObjectName("programmer_cb")
        self.verticalLayout.addWidget(self.programmer_cb)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel_btn = QtWidgets.QPushButton(ProgrammerDialog)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.program_btn = QtWidgets.QPushButton(ProgrammerDialog)
        self.program_btn.setEnabled(False)
        self.program_btn.setObjectName("program_btn")
        self.horizontalLayout.addWidget(self.program_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.status_lbl = QtWidgets.QLabel(ProgrammerDialog)
        self.status_lbl.setText("")
        self.status_lbl.setObjectName("status_lbl")
        self.verticalLayout.addWidget(self.status_lbl)

        self.retranslateUi(ProgrammerDialog)
        self.cancel_btn.clicked.connect(ProgrammerDialog.reject)
        self.program_btn.clicked.connect(ProgrammerDialog.start_programming)
        self.programmer_cb.popup_shown.connect(ProgrammerDialog.populate_programmers)
        QtCore.QMetaObject.connectSlotsByName(ProgrammerDialog)

    def retranslateUi(self, ProgrammerDialog):
        _translate = QtCore.QCoreApplication.translate
        ProgrammerDialog.setWindowTitle(_translate("ProgrammerDialog", "Programming"))
        self.cancel_btn.setText(_translate("ProgrammerDialog", "Close"))
        self.program_btn.setText(_translate("ProgrammerDialog", "Program"))
from qcomboboxextra import QComboBoxExtra


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProgrammerDialog = QtWidgets.QDialog()
    ui = Ui_ProgrammerDialog()
    ui.setupUi(ProgrammerDialog)
    ProgrammerDialog.show()
    sys.exit(app.exec_())
